### ISSUE TITLE
Use custom storage container for hub storage rather than enderchest

### ISSUE THREAD

**Issue by Derongan** [MineInAbyss/MineInAbyss#65]
Im concerned about using the enderChest in all cases. Maybe in a future change we can instead use a custom storage container.

_Originally posted by @Derongan in https://github.com/MineInAbyss/MineInAbyss/pull/64#discussion_r554672732_

**Comment by 0ffz** [comment]
👍 For this. We may want more pages, etc... There are already vault plugins out there, not sure if we want to rely on anyone else's api for this though.

Either way, I've already written an `ItemStackSerializer` in Idofront that serializes it to a string through Bukkit's serializer. It's barely human readable but should be completely version safe since spigot handles migrations for us there. We could easily store a list of them, or a more complex structure depending on what we want. Perhaps make a serializer for a chest inventory then store a list of them and allow you to list through them via guiy?
